### PR TITLE
1.19.4 support

### PR DESCRIPTION
**Pull request by MelonHell**

### CODE REVIEW

**Comment by mworzala** [comment]
I havent looked deep into it, but what is missing here? (ie marked as draft)

**Comment by MelonHell** [comment]
This is moving old commits to a new branch and updating from snapshot to release.  It works, but I'm not sure if all the new content has been added or is working properly

**Comment by Codestech1** [comment]
@MelonHell If you made it by forking main Minestom repository i think you should create pr in that.

**Comment by mworzala** [comment]
Closing in favor of #11

**Pull request closed without merging**
